package database;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Random;

/**
 * Generates a realistic <b>PLACEHOLDER</b> dataset for a Ghanaian hospital/clinic
 * network so the whole system is runnable while the Database Team finalises the
 * real seed data. Output goes to {@code database/seed-data/} as four CSVs whose
 * headers match the raw templates in {@code /data/}.
 *
 * <p>Every generated file begins with a {@code # PLACEHOLDER} banner line (which
 * {@link DataLoader} skips) so it is obvious at a glance that the data is
 * synthetic and must be swapped for the real collection. The generator is
 * deterministic (fixed random seed) so results are reproducible.</p>
 *
 * <p>Sizes exceed the brief's minimums: 60 locations, ~150 routes (connected),
 * 320 service requests, 36 resources.</p>
 *
 * <p>Run with: {@code java -cp out/main database.SeedDataGenerator}</p>
 */
public final class SeedDataGenerator {

    private static final String BANNER =
        "# PLACEHOLDER DATA — auto-generated by database.SeedDataGenerator. " +
        "Replace with the real Database Team dataset. See report/README-for-documentation-team.md.";

    // Pools of realistic hospital location names / areas / types.
    private static final String[] DEPARTMENTS = {
        "Emergency Department", "Outpatient Department", "Radiology", "Pharmacy",
        "Laboratory", "Theatre", "Maternity", "Antenatal Clinic", "Paediatrics",
        "Physiotherapy", "Dental Clinic", "Eye Clinic", "ENT Clinic", "Dialysis Unit",
        "Blood Bank", "Mortuary", "Records Office", "Admissions", "Cashier / Billing",
        "Intensive Care Unit", "Coronary Care Unit", "Burns Unit", "Oncology",
        "Chemotherapy Suite", "Endoscopy", "Ultrasound", "CT Scan Suite", "MRI Suite",
        "Central Sterile Supply", "Kitchen / Catering", "Laundry", "Chapel",
        "Staff Canteen", "Pharmacy Store", "Oxygen Plant", "Generator House"
    };
    private static final String[] WARD_PREFIX = { "Ward", "Recovery Bay", "Isolation Room" };
    private static final String[] AREAS = {
        "Main Block", "Maternity Block", "Surgical Block", "OPD Block",
        "Emergency Block", "Administration Block", "Support Services", "Annexe"
    };
    private static final String[] REQUEST_CATEGORIES = {
        "patient-transfer", "lab-sample", "equipment-delivery", "medication-run",
        "cleaning", "porter-escort", "blood-delivery", "specimen-collection"
    };
    private static final String[] RESOURCE_TYPES = {
        "nurse", "porter", "ambulance", "wheelchair", "trolley", "doctor",
        "lab-tech", "cleaner", "oxygen-cylinder"
    };
    private static final String[] AVAIL = { "AVAILABLE", "AVAILABLE", "AVAILABLE", "BUSY", "OFFLINE" };

    public static void main(String[] args) throws IOException {
        Path outDir = Path.of("database", "seed-data");
        Files.createDirectories(outDir);
        Random rng = new Random(20260811L); // fixed seed => reproducible dataset

        int nLocations = 60;
        int nResources = 36;
        int nRequests  = 320;

        String[] locIds = writeLocations(outDir, nLocations, rng);
        writeRoutes(outDir, locIds, rng);
        writeResources(outDir, locIds, nResources, rng);
        writeRequests(outDir, locIds, nRequests, rng);

        System.out.println("Placeholder seed data written to " + outDir.toAbsolutePath());
    }

    private static String[] writeLocations(Path dir, int n, Random rng) throws IOException {
        String[] ids = new String[n];
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(dir.resolve("locations.csv")))) {
            w.println(BANNER);
            w.println("locationId,name,area,type,notes");
            for (int i = 0; i < n; i++) {
                String id = String.format("L%03d", i + 1);
                ids[i] = id;
                String name; String type;
                if (i < DEPARTMENTS.length) {          // first: named departments
                    name = DEPARTMENTS[i];
                    type = name.contains("Unit") || name.contains("ICU") ? "unit" : "department";
                } else {                                // remainder: numbered wards/bays
                    String pfx = WARD_PREFIX[rng.nextInt(WARD_PREFIX.length)];
                    name = pfx + " " + (char) ('A' + rng.nextInt(6)) + (1 + rng.nextInt(9));
                    type = "ward";
                }
                String area = AREAS[rng.nextInt(AREAS.length)];
                w.printf("%s,%s,%s,%s,%s%n", id, csv(name), csv(area), type, "placeholder");
            }
        }
        return ids;
    }

    private static void writeRoutes(Path dir, String[] locIds, Random rng) throws IOException {
        int n = locIds.length;
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(dir.resolve("routes.csv")))) {
            w.println(BANNER);
            w.println("fromLocationId,toLocationId,distance,travelTime,notes");
            boolean[][] seen = new boolean[n][n];
            int edges = 0;
            // 1) A spanning chain guarantees the whole network is connected.
            for (int i = 1; i < n; i++) {
                int j = rng.nextInt(i); // link i to some earlier node
                writeEdge(w, locIds, i, j, seen, rng);
                edges++;
            }
            // 2) Extra random corridors to reach ~150 edges and add alternate routes.
            while (edges < 150) {
                int a = rng.nextInt(n), b = rng.nextInt(n);
                if (a == b || seen[a][b]) continue;
                writeEdge(w, locIds, a, b, seen, rng);
                edges++;
            }
        }
    }

    private static void writeEdge(PrintWriter w, String[] locIds, int a, int b,
                                  boolean[][] seen, Random rng) {
        seen[a][b] = seen[b][a] = true;
        int distance = 20 + rng.nextInt(400);          // metres
        int travel   = distance / 2 + 10 + rng.nextInt(60); // seconds (roughly ~walking)
        w.printf("%s,%s,%d,%d,%s%n", locIds[a], locIds[b], distance, travel, "placeholder");
    }

    private static void writeResources(Path dir, String[] locIds, int n, Random rng) throws IOException {
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(dir.resolve("resources.csv")))) {
            w.println(BANNER);
            w.println("resourceId,type,homeLocation,capacity,availabilityStatus");
            for (int i = 0; i < n; i++) {
                String id = String.format("R%03d", i + 1);
                String type = RESOURCE_TYPES[rng.nextInt(RESOURCE_TYPES.length)];
                String home = locIds[rng.nextInt(locIds.length)];
                int capacity = 30 + rng.nextInt(90);   // available minutes in window
                String status = AVAIL[rng.nextInt(AVAIL.length)];
                w.printf("%s,%s,%s,%d,%s%n", id, type, home, capacity, status);
            }
        }
    }

    private static void writeRequests(Path dir, String[] locIds, int n, Random rng) throws IOException {
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(dir.resolve("service-requests.csv")))) {
            w.println(BANNER);
            w.println("requestId,source,destination,category,urgency,timeSubmitted,deadline,status");
            for (int i = 0; i < n; i++) {
                String id = String.format("SR%04d", i + 1);
                String src = locIds[rng.nextInt(locIds.length)];
                String dst = locIds[rng.nextInt(locIds.length)];
                while (dst.equals(src)) dst = locIds[rng.nextInt(locIds.length)];
                String cat = REQUEST_CATEGORIES[rng.nextInt(REQUEST_CATEGORIES.length)];
                int urgency = 1 + rng.nextInt(5);      // 1 (critical) .. 5 (routine)
                int hour = 6 + rng.nextInt(14);        // submitted 06:00–19:00
                int min  = rng.nextInt(60);
                String submitted = String.format("2026-08-11T%02d:%02d", hour, min);
                int leadMin = 15 + rng.nextInt(180);
                int dHour = hour + (min + leadMin) / 60, dMin = (min + leadMin) % 60;
                if (dHour > 23) dHour = 23;
                String deadline = String.format("2026-08-11T%02d:%02d", dHour, dMin);
                String status = "PENDING";
                w.printf("%s,%s,%s,%s,%d,%s,%s,%s%n", id, src, dst, cat, urgency, submitted, deadline, status);
            }
        }
    }

    /** Quote a CSV field only if it contains a comma. */
    private static String csv(String s) { return s.contains(",") ? "\"" + s + "\"" : s; }

    private SeedDataGenerator() {}
}
