#!/usr/bin/env python3
"""
Generate the location index: one tuple per campus location, in the form

    ('New N Block','G4-522-1894','02', 'Lecture Hall')
      name         digital addr   cat   category label

Field 3 is the two-digit category ordinal, taken from the order categories are
declared in schema.sql's ck_loc_category CHECK. Field 4 is that category's
singular display label.

Field 2 (the GhanaPost GPS digital address) is NOT in locations.csv. It is read
from an optional side file so the index can be regenerated as addresses arrive:

    python make_location_index.py                       # blank address slots
    python make_location_index.py data/addresses.csv    # filled in

addresses.csv must have a header and two columns: location_code,digital_address

Re-run after Role 2 delivers new CSVs. Output: location_index.sql
"""

import csv
import sys
from pathlib import Path

HERE = Path(__file__).parent
LOCATIONS_CSV = HERE / "data" / "locations.csv"
OUTPUT_SQL = HERE / "location_index.sql"

# Order is significant: position in this list IS the two-digit code in field 3.
# It mirrors schema.sql's ck_loc_category CHECK exactly — keep the two in sync.
CATEGORIES = [
    ("departments",   "Department"),
    ("lecture-halls", "Lecture Hall"),
    ("libraries",     "Library"),
    ("research",      "Research Centre"),
    ("landmarks",     "Landmark"),
    ("residences",    "Residence"),
    ("hostels",       "Hostel"),
    ("food",          "Food Service"),
    ("health",        "Health Facility"),
    ("banking",       "Banking"),
    ("sports",        "Sports Facility"),
    ("offices",       "Office"),
    ("ict",           "ICT Facility"),
    ("childcare",     "Childcare"),
    ("hotspots",      "Hotspot"),
    ("transport",     "Transport"),
    ("worship",       "Place of Worship"),
]

CODE = {slug: f"{i:02d}" for i, (slug, _) in enumerate(CATEGORIES, start=1)}
LABEL = dict(CATEGORIES)


def sql_quote(value):
    """Single-quote a string for SQL, doubling any embedded quote."""
    return "'" + value.replace("'", "''") + "'"


def load_addresses(path):
    """location_code -> digital address. Missing file is not an error."""
    if path is None:
        return {}
    with open(path, newline="", encoding="utf-8") as fh:
        return {
            row["location_code"]: row["digital_address"].strip()
            for row in csv.DictReader(fh)
        }


def main():
    addresses = load_addresses(sys.argv[1] if len(sys.argv) > 1 else None)

    with open(LOCATIONS_CSV, newline="", encoding="utf-8") as fh:
        locations = list(csv.DictReader(fh))

    rows, unknown, missing_addr = [], [], []

    for loc in locations:
        category = loc["category"]
        if category not in CODE:
            unknown.append((loc["location_code"], category))
            continue

        address = addresses.get(loc["location_code"], "")
        if not address:
            missing_addr.append(loc["location_code"])

        rows.append(
            "({}, {}, {}, {})".format(
                sql_quote(loc["name"]),
                sql_quote(address),
                sql_quote(CODE[category]),
                sql_quote(LABEL[category]),
            )
        )

    header = [
        "-- Location index — generated by make_location_index.py, do not hand-edit.",
        "-- Format: (name, digital_address, category_code, category_label)",
        f"-- {len(rows)} locations from data/locations.csv",
    ]
    if missing_addr:
        header.append(
            f"-- WARNING: {len(missing_addr)} of {len(rows)} digital addresses are "
            "EMPTY — no source data. Supply an addresses.csv and re-run."
        )

    body = ",\n".join(rows)
    OUTPUT_SQL.write_text("\n".join(header) + "\n\n" + body + ";\n", encoding="utf-8")

    print(f"Wrote {len(rows)} tuples to {OUTPUT_SQL.name}")
    if missing_addr:
        print(f"  {len(missing_addr)} blank digital addresses")
    for code, category in unknown:
        print(f"  SKIPPED {code}: category {category!r} not in schema CHECK list")


if __name__ == "__main__":
    main()
